services:
  - type: web
    name: school-manager
    env: dotnet
    buildCommand: dotnet publish -c Release
    startCommand: dotnet SchoolManager.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: school-manager-db
          property: connectionString

databases:
  - name: school-manager-db
    databaseName: SchoolManagement
    user: postgres
    plan: free 